### ISSUE TITLE
I want the orcaslicer to upload files to ad5m. What should I do?

### ISSUE THREAD

**Issue by 50617546** [g992/flashforge-ad5m-5mpro-research#1]
I want the orcaslicer to upload files to ad5m. What should I do?

**Comment by g992** [comment]
> I want the orcaslicer to upload files to ad5m. What should I do?
> 
> 
> 
> 

Its hard. Flashforge uses own protocol, based on low-level tcp. U can find some repos with it implementation, but no one not realise uploading file.  

I want to remove the proprietary flashforge software and install Moonraker, but I don't know if it has enough RAM to run it. 128 mb is really not enough.

I also don’t know whether it’s worth losing all this flashforge functionality, because there are some useful things among it.

**Comment by xblax** [comment]
Apparently someone forked Orca Slicer and implemented this functionality: https://github.com/iherbak/OrcaSlicer
